package:
  name: imp
  version: "2.5.0"

source:
  fn: imp-2.5.0.tar.gz
  url: http://integrativemodeling.org/2.5.0/download/imp-2.5.0.tar.gz
  md5: a283a80d8cd953fdd15e6c9f8dabbbc0
  patches:
    - cmake-path.patch [win]
    - cmake-policy.patch [win]
    - imp-session.patch [win]
    - rmf-vmdplugin.patch [win]
    - imp-setup-module.patch [win]
    - rmf-decorators.patch [win]
    - rmf-hash-value.patch [win]
    - imp-symlink.patch [win]
    - imp-utf8-encoding.patch [win]
    - imp-directories.patch [win]
    - pmi-hierarchy-mass.patch

build:
  number: 5
  detect_binary_files_with_prefix: True

requirements:
  build:
    - python
    - swig
    - cgal
    - cmake [not osx and not win]
    - cmake-mac [osx or win]
    - boost [not osx]
    - boost-mac [osx]
    - hdf5
    - fftw
    - libtau
    - gsl
    - opencv [py2k and not win]
    - opencv-nopython [py3k or win]

  run:
    - python
    - cgal
    - boost [not osx]
    - boost-mac [osx]
    - hdf5
    - fftw
    - libtau
    - gsl
    - opencv [py2k and not win]
    - opencv-nopython [py3k or win]

test:
  # Python imports
  imports:
    - IMP
    - IMP.atom
    - IMP.cgal
    - IMP.cnmultifit
    - IMP.em2d
    - IMP.rmf
    - RMF
  # Command line tools
  commands:
    - cnmultifit --help
    - foxs --help

about:
  home: http://integrativemodeling.org
  license: LGPL/GPL
  summary: "The Integrative Modeling Platform"
