package:
  name: imp
  version: "2.5.0"

source:
  fn: imp-2.5.0.tar.gz
  url: http://integrativemodeling.org/2.5.0/download/imp-2.5.0.tar.gz
  md5: a283a80d8cd953fdd15e6c9f8dabbbc0

build:
  number: 0

requirements:
  build:
    - python
    - swig
    - cgal [osx]
    - cmake [not osx and not win]
    - cmake-mac [osx or win]
    - boost [not osx]
    - boost-mac [osx]
    - hdf5
    - fftw
    - libtau
    - gsl
    - opencv [py2k and not win]
    - opencv-nopython [py3k and not win]

  run:
    - python
    - cgal [osx]
    - boost [not osx]
    - boost-mac [osx]
    - hdf5
    - fftw
    - libtau
    - gsl
    - opencv [py2k and not win]
    - opencv-nopython [py3k and not win]

test:
  # Python imports
  imports:
    - IMP
    - IMP.atom
    - IMP.cnmultifit
    - IMP.em2d
    - IMP.rmf
    - RMF

about:
  home: http://integrativemodeling.org
  license: LGPL/GPL
  summary: "The Integrative Modeling Platform"
