package:
  name: imp
  version: "2.6.2"

source:
  fn: imp-2.6.2.tar.gz
  url: http://integrativemodeling.org/2.6.2/download/imp-2.6.2.tar.gz
  sha256: d048d1d0d867d4bc98de1ff1953118569b4be36c2198bc7538a7a503f7e9b853
  patches:
    - imp-directories.patch [win]

build:
  number: 1
  detect_binary_files_with_prefix: True [not win]
  features:
    - vc9 [win and py27]
    - vc14 [win and py35]

requirements:
  build:
    - python
    - swig
    - cgal 4.9
    - cmake [not osx and not win]
    - cmake-mac [osx or win]
    - boost 1.60.0 [win]
    - boost 1.57.0 [linux]
    - boost-mac [osx]
    - hdf5 1.8.17
    - fftw 3.3.4
    - libtau
    - gsl 1.8 [win]
    - gsl 1.16 [not win]
    - opencv 2.4.8 [py2k and osx]
    - opencv 2.4.6 [py2k and linux32]
    - opencv 2.4.10 [py2k and linux64]
    - opencv-nopython 2.4.9 [py3k or win]

  run:
    - python
    - cgal 4.9
    - boost 1.60.0 [win]
    - boost 1.57.0 [linux]
    - boost-mac [osx]
    - hdf5 1.8.17
    - fftw 3.3.4
    - libtau
    - gsl 1.8 [win]
    - gsl 1.16 [not win]
    - opencv 2.4.8 [py2k and osx]
    - opencv 2.4.6 [py2k and linux32]
    - opencv 2.4.10 [py2k and linux64]
    - opencv-nopython 2.4.9 [py3k or win]

test:
  # Python imports
  imports:
    - IMP
    - IMP.atom
    - IMP.cgal
    - IMP.cnmultifit
    - IMP.em2d
    - IMP.rmf
    - RMF
  # Command line tools
  commands:
    - cnmultifit --help
    - foxs --help

about:
  home: https://integrativemodeling.org
  license: LGPL/GPL
  summary: "The Integrative Modeling Platform"
