package:
  name: imp
  version: "2.6.0"

source:
  fn: imp-2.6.0.tar.gz
  url: http://integrativemodeling.org/2.6.0/download/imp-2.6.0.tar.gz
  sha256: 66ab0edbb3226d0f88d1d34afcca88a34ffddb00d2c7400aad5520bc90e88d05
  patches:
    - imp-directories.patch [win]

build:
  number: 1
  detect_binary_files_with_prefix: True

requirements:
  build:
    - python
    - swig
    - cgal
    - cmake [not osx and not win]
    - cmake-mac [osx or win]
    - boost [not osx]
    - boost-mac [osx]
    - hdf5
    - fftw
    - libtau
    - gsl
    - opencv [py2k and not win]
    - opencv-nopython [py3k or win]

  run:
    - python
    - cgal
    - boost [not osx]
    - boost-mac [osx]
    - hdf5
    - fftw
    - libtau
    - gsl
    - opencv [py2k and not win]
    - opencv-nopython [py3k or win]

test:
  # Python imports
  imports:
    - IMP
    - IMP.atom
    - IMP.cgal
    - IMP.cnmultifit
    - IMP.em2d
    - IMP.rmf
    - RMF
  # Command line tools
  commands:
    - cnmultifit --help
    - foxs --help

about:
  home: http://integrativemodeling.org
  license: LGPL/GPL
  summary: "The Integrative Modeling Platform"
