package:
  name: imp
  version: "2.8.0"

source:
  fn: imp-2.8.0.tar.gz
  url: https://integrativemodeling.org/2.8.0/download/imp-2.8.0.tar.gz
  sha256: 83a23c56f0be9de8900d0edd3978eb8c2637e6d5086f7ef7e2cd61f0b7a5aa80
  patches:
    - cgal-test.patch [not win]
    - cgal-test-dos.patch [win]
    - cgal-4.11.patch
    - domino-no-inline.patch
    - imp-directories.patch [win]

build:
  number: 3
  detect_binary_files_with_prefix: True [not win]
  features:
    - vc9 [win and py27]
    - vc14 [win and py36]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python
    - swig
    - cgal 4.12
    - cmake [not win]
    - cmake-mac [win]
    - boost 1.61.0 [win]
    - boost 1.65.1 [not win]
    - hdf5 1.10.1
    - fftw 3.3.4
    - libtau
    - gsl 1.8 [win]
    - gsl 2.4 [not win]
    - opencv 3.3.1
    - protobuf 3.4.1  # 3.5.1 is available but opencv needs 3.4.1
    - openmpi [osx]
    - mpich2 [linux]
      # For windows, need to install Microsoft MPI

  run:
    - python
    - cgal 4.12
    - boost 1.61.0 [win]
    - boost 1.65.1 [not win]
    - hdf5 1.10.1
    - fftw 3.3.4
    - libtau
    - gsl 1.8 [win]
    - gsl 2.4 [not win]
    - opencv 3.3.1
    - protobuf 3.4.1
    - openmpi [osx]
    - mpich2 [linux]

test:
  # Python imports
  imports:
    - IMP
    - IMP.atom
    - IMP.cgal
    - IMP.cnmultifit
    - IMP.em2d
    - IMP.rmf
    - IMP.mpi
    - IMP.spb
    - RMF
  # Command line tools
  commands:
    - cnmultifit --help
    - foxs --help
    - spb_test_score --help

about:
  home: https://integrativemodeling.org
  license: LGPL/GPL
  summary: "The Integrative Modeling Platform"
  description: >
    IMP's broad goal is to contribute to a comprehensive structural
    characterization of biomolecules ranging in size and complexity from small
    peptides to large macromolecular assemblies, by integrating data from
    diverse biochemical and biophysical experiments. IMP provides an open
    source C++ and Python toolbox for solving complex modeling problems, and a
    number of applications for tackling some common problems in a user-friendly
    way. IMP can also be used from the
    [Chimera](http://www.cgl.ucsf.edu/chimera/) molecular modeling system,
    or via one of several web applications.

    See [the IMP website](https://integrativemodeling.org/) for more details.

    If you have problems with this conda package, please
    [open an issue](https://github.com/salilab/conda-recipes/issues).
