package:
  name: imp
  version: "2.9.0"

source:
  fn: imp-2.9.0.tar.gz
  url: https://integrativemodeling.org/2.9.0/download/imp-2.9.0.tar.gz
  sha256: 4fb6f15a2e598cecfd374c701ba5f59fb39d28b02ec44e9ef162dc8cf8e33fd0
  patches:
    - imp-directories.patch [win]
    - npctransport-dos.patch [win]

build:
  number: 1
  detect_binary_files_with_prefix: True [not win]

requirements:
  host:
    - python {{ python }}
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python {{ python }}
    - swig
    - cgal 4.12.*
    - eigen
    - cmake
    - boost 1.65.1.*
    - hdf5 1.10.2.*
    - fftw 3.3.4.*
    - libtau 1.0.1.* [win]
    - libtau 1.0.2.* [not win]
    - gsl 1.8.* [win]
    - gsl 2.4.* [not win]
    - opencv 3.4.1.*
    - protobuf 3.5.2.*
    - openmpi [osx]
    - mpich2 [linux]
      # For windows, need to install Microsoft MPI

  run:
    - python {{ python }}
    - cgal 4.12.*
    - libboost 1.65.1.*
    - hdf5 1.10.2.*
    - fftw 3.3.4.*
    - libtau 1.0.1.* [win]
    - libtau 1.0.2.* [not win]
    - gsl 1.8.* [win]
    - gsl 2.4.* [not win]
    - opencv 3.4.1.*
    - protobuf 3.5.2.*
    - openmpi [osx]
    - mpich2 [linux]

test:
  # Python imports
  imports:
    - IMP
    - IMP.atom
    - IMP.cgal
    - IMP.cnmultifit
    - IMP.em2d
    - IMP.npc
    - IMP.npctransport
    - IMP.rmf
    - IMP.mpi
    - IMP.spb
    - RMF
  # Command line tools
  commands:
    - cnmultifit --help
    - foxs --help
    - spb_test_score --help

about:
  home: https://integrativemodeling.org
  license: LGPL/GPL
  summary: "The Integrative Modeling Platform"
  description: >
    IMP's broad goal is to contribute to a comprehensive structural
    characterization of biomolecules ranging in size and complexity from small
    peptides to large macromolecular assemblies, by integrating data from
    diverse biochemical and biophysical experiments. IMP provides an open
    source C++ and Python toolbox for solving complex modeling problems, and a
    number of applications for tackling some common problems in a user-friendly
    way. IMP can also be used from the
    [Chimera](http://www.cgl.ucsf.edu/chimera/) molecular modeling system,
    or via one of several web applications.

    See [the IMP website](https://integrativemodeling.org/) for more details.

    If you have problems with this conda package, please
    [open an issue](https://github.com/salilab/conda-recipes/issues).
