package:
  name: imp
  version: "2.8.0"

source:
  fn: imp-2.8.0.tar.gz
  url: https://integrativemodeling.org/2.8.0/download/imp-2.8.0.tar.gz
  sha256: 83a23c56f0be9de8900d0edd3978eb8c2637e6d5086f7ef7e2cd61f0b7a5aa80
  patches:
    - cgal-test.patch [linux]
    - imp-directories.patch [win]

build:
  number: 1
  detect_binary_files_with_prefix: True [not win]
  features:
    - vc9 [win and py27]
    - vc14 [win and py36]

requirements:
  build:
    - python
    - swig
    - cgal 4.10
    - cmake [not win]
    - cmake-mac [win]
    - boost 1.61.0 [win]
    - boost 1.61.0 [linux]
    - boost 1.61.0 [osx]
    - hdf5 1.8.17
    - fftw 3.3.4
    - libtau
    - gsl 1.8 [win]
    - gsl 2.4 [not win]
    - opencv 2.4.8 [py2k and osx]
    - opencv 2.4.6 [py2k and linux32]
    - opencv 3.1.0 [py2k and linux64]
    - numpy 1.11* [py2k and linux64]
    - opencv-nopython 2.4.9 [py3k or win]
    - openmpi [osx]
    - mpich2 [linux]
      # For windows, need to install Microsoft MPI

  run:
    - python
    - cgal 4.10
    - boost 1.61.0 [win]
    - boost 1.61.0 [linux]
    - boost 1.61.0 [osx]
    - hdf5 1.8.17
    - fftw 3.3.4
    - libtau
    - gsl 1.8 [win]
    - gsl 2.4 [not win]
    - opencv 2.4.8 [py2k and osx]
    - opencv 2.4.6 [py2k and linux32]
    - opencv 3.1.0 [py2k and linux64]
    - numpy 1.11* [py2k and linux64]
    - opencv-nopython 2.4.9 [py3k or win]
    - openmpi [osx]
    - mpich2 [linux]

test:
  # Python imports
  imports:
    - IMP
    - IMP.atom
    - IMP.cgal
    - IMP.cnmultifit
    - IMP.em2d
    - IMP.rmf
    - IMP.mpi
    - IMP.spb
    - RMF
  # Command line tools
  commands:
    - cnmultifit --help
    - foxs --help
    - spb_test_score --help

about:
  home: https://integrativemodeling.org
  license: LGPL/GPL
  summary: "The Integrative Modeling Platform"
