package:
  name: imp
  version: "2.6.1"

source:
  fn: imp-2.6.1.tar.gz
  url: http://integrativemodeling.org/2.6.1/download/imp-2.6.1.tar.gz
  sha256: ed9ecea7469843a3340ebd62ae3e4705c4454d733e341ea91aa19d334e4573b8
  patches:
    - imp-directories.patch [win]

build:
  number: 1
  detect_binary_files_with_prefix: True
  features:
    - vc9 [win and py27]
    - vc14 [win and py35]

requirements:
  build:
    - python
    - swig 3.0.7 [win]
    - swig 3.0.2 [not win]
    - cgal 4.7 [win]
    - cgal 4.6.1 [not win]
    - cmake [not osx and not win]
    - cmake-mac [osx or win]
    - boost [not osx]
    - boost-mac [osx]
    - hdf5 1.8.16
    - fftw
    - libtau
    - gsl
    - opencv [py2k and not win]
    - opencv-nopython [py3k or win]

  run:
    - python
    - cgal 4.7 [win]
    - cgal 4.6.1 [not win]
    - boost [not osx]
    - boost-mac [osx]
    - hdf5 1.8.16
    - fftw
    - libtau
    - gsl
    - opencv [py2k and not win]
    - opencv-nopython [py3k or win]

test:
  # Python imports
  imports:
    - IMP
    - IMP.atom
    - IMP.cgal
    - IMP.cnmultifit
    - IMP.em2d
    - IMP.rmf
    - RMF
  # Command line tools
  commands:
    - cnmultifit --help
    - foxs --help

about:
  home: https://integrativemodeling.org
  license: LGPL/GPL
  summary: "The Integrative Modeling Platform"
