package:
  name: imp
  version: "2.11.1"

source:
  fn: imp-2.11.1.tar.gz [not win]
  url: https://integrativemodeling.org/2.11.1/download/imp-2.11.1.tar.gz [not win]
  sha256: 1777ef37aaf79d37c737923c56b9f2f27dc84cb7ab0f4f56fd146c90168ece45 [not win]
  fn: imp-2.11.1.zip [win]
  url: https://integrativemodeling.org/2.11.1/download/imp-2.11.1.zip [win]
  sha256: c75c1d40bc23a62ec7e976704d12adb92646421e8eb1d267fa2cf2561974b50d [win]
  patches:
    - imp-directories.patch [win]
    - vs2008-ice-dos.patch [win and py27]

build:
  number: 1
  detect_binary_files_with_prefix: True [not win]

requirements:
  host:
    - python {{ python }}
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python {{ python }}
    - swig
    - cgal 4.12.* [win and py27]
    - cgal 4.14.* [not win or not py27]
    - eigen
    - cmake [not win or not py27]
    - cmake-mac [win and py27]
    - boost 1.67.0.*
    - hdf5 1.10.2.*
    - fftw 3.3.4.*
    - libtau 1.0.1.* [win]
    - libtau 1.0.2.* [not win]
    - gsl 1.8.* [win]
    - gsl 2.4.* [not win]
    - opencv 3.4.2.* [not win]
    - protobuf 3.6.1.* [linux32]
    - protobuf 3.8.0.* [not win and not linux32]
    - opencv 3.4.1.* [win64 and not py27]
    - opencv 3.4.2.* [win32 and not py27]
    - opencv-nopython 2.4.9.* [win and py27]
    - protobuf 3.5.2.* [win and py27]
    - protobuf 3.6.1.* [win and not py27]
    - openmpi 3.1.3.* [osx]
    - mpich2 1.4.1.* [linux32]
    - mpich 3.2.1.* [linux64]
      # For windows, need to install Microsoft MPI

  run:
    - python {{ python }}
    - cgal 4.12.* [win and py27]
    - cgal 4.14.* [not win or not py27]
    - boost 1.67.0.* [win]
    - libboost 1.67.0.* [not win]
    - hdf5 1.10.2.*
    - fftw 3.3.4.*
    - libtau 1.0.1.* [win]
    - libtau 1.0.2.* [not win]
    - gsl 1.8.* [win]
    - gsl 2.4.* [not win]
    - opencv 3.4.2.* [not win]
    - protobuf 3.6.1.* [linux32]
    - protobuf 3.8.0.* [not win and not linux32]
    - opencv 3.4.1.* [win64 and not py27]
    - opencv 3.4.2.* [win32 and not py27]
    - opencv-nopython 2.4.9.* [win and py27]
    - protobuf 3.5.2.* [win and py27]
    - protobuf 3.6.1.* [win and not py27]
    - openmpi 3.1.3.* [osx]
    - mpich2 1.4.1.* [linux32]
    - mpich 3.2.1.* [linux64]

test:
  # Need Eigen to test IMPConfig.cmake
  requires:
    - eigen
  # Python imports
  imports:
    - IMP
    - IMP.atom
    - IMP.cgal
    - IMP.cnmultifit
    - IMP.em2d
    - IMP.npc
    - IMP.npctransport
    - IMP.rmf
    - IMP.mpi
    - IMP.spb
    - RMF
  # Command line tools
  commands:
    - cnmultifit --help
    - foxs --help
    - spb_test_score --help

about:
  home: https://integrativemodeling.org
  license: LGPL/GPL
  summary: "The Integrative Modeling Platform"
  description: >
    IMP's broad goal is to contribute to a comprehensive structural
    characterization of biomolecules ranging in size and complexity from small
    peptides to large macromolecular assemblies, by integrating data from
    diverse biochemical and biophysical experiments. IMP provides an open
    source C++ and Python toolbox for solving complex modeling problems, and a
    number of applications for tackling some common problems in a user-friendly
    way. IMP can also be used from the
    [Chimera](http://www.cgl.ucsf.edu/chimera/) molecular modeling system,
    or via one of several web applications.

    See [the IMP website](https://integrativemodeling.org/) for more details.

    If you have problems with this conda package, please
    [open an issue](https://github.com/salilab/conda-recipes/issues).
