package:
  name: fftw
  version: 3.3.4

source:
  fn: fftw-3.3.4.tar.gz [not win]
  url: http://www.fftw.org/fftw-3.3.4.tar.gz [not win]
  sha256: 8f0cde90929bc05587c3368d2f15cd0530a60b8a9912a8e2979a72dbe5af0982 [not win]
  fn: fftw-3.3.4-dll32.zip [win32]
  url: ftp://ftp.fftw.org/pub/fftw/fftw-3.3.4-dll32.zip [win32]
  sha256: 57535a9fec2e009dbd6adcb99b850980cde981e3a9d751e74ec9401d76b51808 [win32]
  fn: fftw-3.3.4-dll64.zip [win64]
  url: ftp://ftp.fftw.org/pub/fftw/fftw-3.3.4-dll64.zip [win64]
  sha256: 8b0d9f04888918e23a50949c9dd3838486cd1c4d584c21349da3fe01a0c4c7f6 [win64]

build:
  number: 1

requirements:
  build:
    - chrpath [linux]

about:
  home: http://www.fftw.org/
  summary: 'Fastest Fourier Transform in the West'
  license: GPL2
  description: >
    FFTW is a C subroutine library for computing the discrete Fourier
    transform (DFT) in one or more dimensions, of arbitrary input size,
    and of both real and complex data (as well as of even/odd data, i.e.
    the discrete cosine/sine transforms or DCT/DST). We believe that FFTW,
    which is free software, should become the FFT library of choice for
    most applications.

    See the [FFTW website](http://www.fftw.org/) for more information.

    If you have problems with this conda package, please
    [open an issue](https://github.com/salilab/conda-recipes/issues).
