# Tested on Mac OS X 10.9 using clang compiler provided by XCode
package:
    name: opencv-nopython
    version: 2.4.9

source:
    fn: opencv-2.4.9.zip
    url: http://downloads.sourceforge.net/project/opencvlibrary/opencv-unix/2.4.9/opencv-2.4.9.zip

build:
    number: 2
    features:
      - vc9 [win and py27]
      - vc14 [win and py35]

requirements:
    build:
        - python [win]
        - cmake [not osx and not win]
        - cmake-mac [osx or win]
        - jpeg
        - zlib
        - libpng
        - libtiff
    run:
        - jpeg
        - zlib
        - libpng
        - libtiff

about:
    home: http://opencv.org/
    summary: "opencv package built without Python (for Python 3)"
    license: BSD
