package:
  name: mdt
  version: "5.4"

source:
  fn: mdt-5.4.tar.gz
  url: https://salilab.org/mdt/5.4/mdt-5.4.tar.gz
  sha256: fc403b8c26365c11bd9522929aef0c3b51dff860fddc8ac446a980acec5a3d44

build:
  number: 1

requirements:
  build:
    - python
    - numpy
    - modeller 9.19
    - cmake [not osx]
    - cmake-mac [osx]
    - swig
    - glib

  run:
    - python
    - numpy
    - modeller 9.19

about:
  home: https://salilab.org/mdt/
  license: GPL2
  summary: "Generate frequency tables used by Modeller and IMP"
