package:
  name: imp-bayesianem
  version: "20191021.9bd15b71"

source:
  fn: bayesianem-master.tar.gz
  url: https://gitlab.pasteur.fr/rpellari/bayesianem/-/archive/master/bayesianem-master.tar.gz
  sha256: 224e61276bae8a59f495f74f5ff07b997c98d630b9ce0b6cee40783885727d82

build:
  number: 0
  detect_binary_files_with_prefix: True [not win]

requirements:
  host:
    - python {{ python }}
    - imp 2.11.1.*
    - eigen
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - swig
    - cmake [not win or not py27]
    - cmake-mac [win and py27]

  run:
    - python {{ python }}
    - imp 2.11.1.*

test:
  # Python imports
  imports:
    - IMP.atom
    - IMP.bayesianem
    - IMP.bayesianem.restraint

about:
  home: https://gitlab.pasteur.fr/rpellari/bayesianem
  license: LGPL
  summary: "IMP module for Bayesian modeling with cryo-EM maps"
  description: >
    This is an addon module for the Integrative Modeling Platform (IMP).
    It is for Bayesian multi-scale modeling of macromolecular structures
    based on cryo-electron microscopy density maps.

    See [the IMP website](https://integrativemodeling.org/)
    and the [Bayesian EM publication](https://doi.org/10.1101/113951)
    for more details.

    If you have problems with this conda package, please
    [open an issue](https://github.com/salilab/conda-recipes/issues).
