package:
  name: cmake-mac
  version: 3.14.6

source:
  fn: cmake-3.14.6.tar.gz [not win]
  url: https://github.com/Kitware/CMake/releases/download/v3.14.6/cmake-3.14.6.tar.gz [not win]
  sha256: 4e8ea11cabe459308671b476469eace1622e770317a15951d7b55a82ccaaccb9 [not win]
  fn: cmake-3.14.6-win32-x86.zip [win32]
  url: https://github.com/Kitware/CMake/releases/download/v3.14.6/cmake-3.14.6-win32-x86.zip [win32]
  sha256: 0000cd8753860658f9eb76909ce1948d904d2f0bb653196e08559f9b16b7218a [win32]
  fn: cmake-3.14.6-win64-x64.zip [win64]
  url: https://github.com/Kitware/CMake/releases/download/v3.14.6/cmake-3.14.6-win64-x64.zip [win64]
  sha256: de8b307391f739b288df1c9edb48e144f31ce1628b907eb37f76ce5025666123 [win64]

test:
  commands:
    - cmake --help

about:
  home: https://www.cmake.org/
  license: BSD
  description: >
    This is a rebuild of the standard conda `cmake` package. That one doesn't
    work on Mac OS X 10.6, and is an older version for Python 2.7 on Windows.
    This is rebuilt on an OS X 10.6 machine, so we can build IMP for older
    Macs (and Windows).

    If you have problems with this conda package, please
    [open an issue](https://github.com/salilab/conda-recipes/issues).
