package:
  name: hdf5-1818 
  version: "1.8.18"

source:
  fn: hdf5-1.8.18.tar.bz2
  url: https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8/hdf5-1.8.18/src/hdf5-1.8.18.tar.bz2
  sha1: d7e008cbfcf5cb6913b5327a81bbcaf34cc9436d
  sha256: 01c6deadf4211f86922400da82c7a8b5b50dc8fc1ce0b5912de3066af316a48c

requirements:
  build:
    - zlib

  run:
    - zlib

about:
  home: http://www.hdfgroup.org/HDF5/
  license: BSD
  summary: "HDF5 pinned at 1.8.18, for use with Modeller"
