package:
  name: modeller
  version: "9.17"

source:
  fn: modeller-9.17-mac.pax.gz [osx]
  url: http://salilab.org/modeller/9.17/modeller-9.17-mac.pax.gz [osx]
  sha256: e8beda6bd8e791ffe1ebf19064f69c945ceec6c9079f30e3becdc3a9584da050 [osx]
  fn: modeller-9.17.tar.gz [linux]
  url: http://salilab.org/modeller/9.17/modeller-9.17.tar.gz [linux]
  sha256: 5489865e54231d448e25ea07ec8822a02657f2ce81763990a84e99c5b6c0edf0 [linux]
  fn: modeller9.17-32bit.zip [win32]
  url: http://salilab.org/modeller/9.17/modeller9.17-32bit.zip [win32]
  sha256: f58454a0e437a6598c1cf5a36dcaa48ef5376d80a1d315283a01df0d7dc967d0 [win32]
  fn: modeller9.17-64bit.zip [win64]
  url: http://salilab.org/modeller/9.17/modeller9.17-64bit.zip [win64]
  sha256: 4220b4badb148900c6cb2b13b45746e652daa4e3e5d4d2b5d51bafb95167a62e [win64]

build:
  number: 1
  rpaths: [linux]
    - lib/modeller-9.17/lib/x86_64-intel8/ [linux64]
    - lib/modeller-9.17/lib/i386-intel8/ [linux32]
    - lib/hdf5-1816 [linux]

requirements:
  build:
    - python
    - swig [unix]
    - setuptools
    - glib [unix]
    - hdf5-1816 [unix]

  run:
    - python
    - hdf5-1816 [unix]

test:
  # Command line tool
  commands:
    - mod9.17 --cflags --libs
    - pkg-config --cflags --libs modeller [unix]
  # Python imports (cannot test without license key)
  #imports:
  #  - modeller

about:
  home: https://salilab.org
  license: Free for academic use
  summary: "Comparative modeling by satisfaction of spatial restraints"
