package:
  name: modeller
  version: "9.15"

source:
  fn: modeller-9.15-mac.pax.gz [osx]
  url: http://salilab.org/modeller/9.15/modeller-9.15-mac.pax.gz [osx]
  md5: 230d615bd876253739c09ed1fd9b9154 [osx]
  fn: modeller-9.15.tar.gz [linux]
  url: http://salilab.org/modeller/9.15/modeller-9.15.tar.gz [linux]
  md5: 3a3cc045b6d05a3314f71a7b9ded1c41 [linux]
  fn: modeller9.15-32bit.zip [win32]
  url: http://salilab.org/modeller/9.15/modeller9.15-32bit.zip [win32]
  sha256: bb32b0889505160fe7ccf00acb5ed194158a6389710fc97fd3f857ddb7a6f3ba [win32]
  fn: modeller9.15-64bit.zip [win64]
  url: http://salilab.org/modeller/9.15/modeller9.15-64bit.zip [win64]
  sha256: 2ffbd0297a1b8ecd1399c6e364e44de248e75be269867600113f71c67e49a4c9 [win64]

build:
  number: 4
  rpaths: [linux]
    - lib/modeller-9.15/lib/x86_64-intel8/ [linux64]
    - lib/modeller-9.15/lib/i386-intel8/ [linux32]
    - lib/hdf5-1813 [linux]

requirements:
  build:
    - python
    - swig [unix]
    - setuptools
    - glib [unix]
    - hdf5-1813

  run:
    - python
    - hdf5-1813

test:
  # Command line tool
  commands:
    - mod9.15 --cflags --libs
  # Python imports (cannot test without license key)
  #imports:
  #  - modeller

about:
  home: http://salilab.org
  license: Free for academic use
  summary: "Comparative modeling by satisfaction of spatial restraints"
