package:
  name: modeller
  version: "9.19"

source:
  fn: modeller-9.19-mac.pax.gz [osx]
  url: https://salilab.org/modeller/9.19/modeller-9.19-mac.pax.gz [osx]
  sha256: 408ebe4176d31709fb897cfc0b5775770e5faaa94edc6eaea9ccc5bd8db6d87e [osx]
  fn: modeller-9.19.tar.gz [linux]
  url: https://salilab.org/modeller/9.19/modeller-9.19.tar.gz [linux]
  sha256: 28be10ca2f4d34836875da6eeed5ffd86256cc75255137c96e001e881685ac4b [linux]
  fn: modeller9.19-32bit.zip [win32]
  url: https://salilab.org/modeller/9.19/modeller9.19-32bit.zip [win32]
  sha256: 006f225c4c1265e984133757168895d4677b08def4ffbd281bd7425d29600312 [win32]
  fn: modeller9.19-64bit.zip [win64]
  url: https://salilab.org/modeller/9.19/modeller9.19-64bit.zip [win64]
  sha256: 49d24561f62a579a57b6da1276a5a3302603299487cbfc50d5c9235d70a31fd5 [win64]

build:
  number: 1
  rpaths: [linux]
    - lib/modeller-9.19/lib/x86_64-intel8/ [linux64]
    - lib/modeller-9.19/lib/i386-intel8/ [linux32]
    - lib/hdf5-1818 [linux]

requirements:
  build:
    - python
    - swig [unix]
    - setuptools
    - glib [unix]
    - hdf5-1818 [unix]

  run:
    - python
    - hdf5-1818 [unix]
    - vs2010_runtime [win32]

test:
  # Command line tool
  commands:
    - mod9.19 --cflags --libs
    - pkg-config --cflags --libs modeller [unix]
  # Python imports (cannot test without license key)
  #imports:
  #  - modeller

about:
  home: https://salilab.org
  license: Free for academic use
  summary: "Comparative modeling by satisfaction of spatial restraints"
