package:
  name: modeller
  version: "9.18"

source:
  fn: modeller-9.18-mac.pax.gz [osx]
  url: https://salilab.org/modeller/9.18/modeller-9.18-mac.pax.gz [osx]
  sha256: 21b6bc7084d2b522c96d886625dba95d222f70f0afa4cfa334d9a1a3a82f8099 [osx]
  fn: modeller-9.18.tar.gz [linux]
  url: https://salilab.org/modeller/9.18/modeller-9.18.tar.gz [linux]
  sha256: ae39723f6ad9d1ebe963cbe6da7a1eecd5f0a7e3c188563628e749e06e946e28 [linux]
  fn: modeller9.18-32bit.zip [win32]
  url: https://salilab.org/modeller/9.18/modeller9.18-32bit.zip [win32]
  sha256: 530595a907c386f86d6fb33e61c299de3d7ef62f27015ea2552c15f6a4b934e2 [win32]
  fn: modeller9.18-64bit.zip [win64]
  url: https://salilab.org/modeller/9.18/modeller9.18-64bit.zip [win64]
  sha256: 5adad21ef2da9882b99a3c191bfd84f9ccb9d02cbc4111e23a29e2613c3e23aa [win64]

build:
  number: 0
  rpaths: [linux]
    - lib/modeller-9.18/lib/x86_64-intel8/ [linux64]
    - lib/modeller-9.18/lib/i386-intel8/ [linux32]
    - lib/hdf5-1817 [linux]

requirements:
  build:
    - python
    - swig [unix]
    - setuptools
    - glib [unix]
    - hdf5-1817 [unix]

  run:
    - python
    - hdf5-1817 [unix]
    - vs2010_runtime [win32]

test:
  # Command line tool
  commands:
    - mod9.18 --cflags --libs
    - pkg-config --cflags --libs modeller [unix]
  # Python imports (cannot test without license key)
  #imports:
  #  - modeller

about:
  home: https://salilab.org
  license: Free for academic use
  summary: "Comparative modeling by satisfaction of spatial restraints"
