package:
  name: modeller
  version: "9.15"

source:
  fn: modeller-9.15-mac.pax.gz [osx]
  url: http://salilab.org/modeller/9.15/modeller-9.15-mac.pax.gz [osx]
  md5: 230d615bd876253739c09ed1fd9b9154 [osx]
  fn: modeller-9.15.tar.gz [linux]
  url: http://salilab.org/modeller/9.15/modeller-9.15.tar.gz [linux]
  md5: 3a3cc045b6d05a3314f71a7b9ded1c41 [linux]

build:
  number: 2
  rpaths: [linux]
    - lib/modeller-9.15/lib/x86_64-intel8/ [linux64]
    - lib/modeller-9.15/lib/i386-intel8/ [linux32]

requirements:
  build:
    - python
    - swig
    - setuptools

  run:
    - python

#test:
  # Python imports
  #imports:
  #  - modeller

about:
  home: http://salilab.org
  license: Free for academic use
  summary: "Comparative modeling by satisfaction of spatial restraints"
