package:
  name: libtau
  version: "1.0.2"

source:
  fn: libTAU-src-1.0.2.tar.gz
  # Source is not public; manually copy the .tar.gz into conda src_cache
  url: https://integrativemodeling.org/libTAU/libTAU-src-1.0.2.tar.gz

build:
  number: 0
  features:
    - vc9 [win and py27]
    - vc14 [win and py35]

requirements:
  build:
    - python [win]
    - scons
    - boost
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

about:
  home: https://integrativemodeling.org/libTAU.html
  license: Binary distribution only
  summary: "Support library needed for MultiFit"
