package:
  name: cgal
  version: "4.7"

source:
  fn: CGAL-4.7.tar.gz
  url: https://github.com/CGAL/cgal/releases/download/releases/CGAL-4.7/CGAL-4.7.tar.gz
  sha256: 1be058fe9fc4d8331b48daf8beb114a049fd4970220d8a570ff709b7789dacae

build:
  number: 0
  features:
    - vc9 [win and py27]
    - vc14 [win and py35]

requirements:
  build:
    - python [win]
    - cmake [not osx and not win]
    - cmake-mac [osx or win]
    - boost 1.60.0 [win]
    - boost-mac 1.57.0 [osx]
    - boost 1.57.0 [not osx and not win]
    - gmp
    - mpfr
    - zlib
  run:
    - boost 1.60.0 [win]
    - boost-mac 1.57.0 [osx]
    - boost 1.57.0 [not osx and not win]
    - gmp
    - mpfr
    - zlib


about:
  home: http://www.cgal.org
  summary: 'The Computational Geometry Algorithms Library'
  license: GPLv3
