package:
  name: cgal
  version: "4.10"

source:
  fn: CGAL-10.tar.xz
  url: https://github.com/CGAL/cgal/releases/download/releases/CGAL-4.10/CGAL-4.10.tar.xz
  sha256: eb56e17dcdecddf6a6fb808931b2142f20aaa182916ddbd912273c51e0f0c045

build:
  number: 1
  features:
    - vc9 [win and py27]
    - vc14 [win and py36]

requirements:
  build:
    - python [win]
    - cmake [not win]
    - cmake-mac [win]
    - boost 1.61.0 [win]
    - boost 1.61.0 [osx]
    - boost 1.61.0 [not osx and not win]
    - gmp
    - mpfr
    - zlib
  run:
    - boost 1.61.0 [win]
    - boost 1.61.0 [osx]
    - boost 1.61.0 [not osx and not win]
    - gmp
    - mpfr
    - zlib


about:
  home: http://www.cgal.org
  summary: 'The Computational Geometry Algorithms Library'
  license: GPL3
