package:
  name: cgal
  version: "4.12" [win and py27]
  version: "4.14" [not win or not py27]

source:
  fn: CGAL-4.14.tar.xz [not win or not py27]
  url: https://github.com/CGAL/cgal/releases/download/releases%2FCGAL-4.14/CGAL-4.14.tar.xz [not win or not py27]
  sha256: 59464b1eaee892f2223ba570a7642892c999e29524ab102a6efd7c29c94a29f7 [not win or not py27]
  fn: CGAL-4.12.tar.xz [win and p27]
  url: https://github.com/CGAL/cgal/releases/download/releases%2FCGAL-4.12/CGAL-4.12.tar.xz [win and py27]
  sha256: 442ef4fffb2ad6e4141e5a7902993ae6a4e73f7cb641fae1010bb586f6ca5e3f [win and py27]

build:
  number: 8

requirements:
  host:
    - python {{ python }} [win]
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python {{ python }} [win]
    - cmake [not win or not py27]
    - cmake-mac [win and py27]
    - boost 1.67.0.*
    - gmp 6.1.2.* [not win]
    - gmp 5.0.1.* [win]
    - mpfr 4.0.1.* [not win]
    - mpfr 3.0.0.* [win]
    - zlib 1.2.11.*
  run:
    - python {{ python }} [win]
    - libboost 1.67.0.*
    - gmp 6.1.2.* [not win]
    - gmp 5.0.1.* [win]
    - mpfr 4.0.1.* [not win]
    - mpfr 3.0.0.* [win]
    - zlib 1.2.11.*


about:
  home: https://www.cgal.org
  summary: 'The Computational Geometry Algorithms Library'
  license: GPL3
  description: >
    The Computational Geometry Algorithms Library (CGAL) is a software
    project that provides easy access to efficient and reliable geometric
    algorithms in the form of a C++ library. CGAL is used in various areas
    needing geometric computation, such as geographic information systems,
    computer aided design, molecular biology, medical imaging, computer
    graphics, and robotics.

    See the [CGAL website](https://www.cgal.org/) for more information.

    If you have problems with this conda package, please
    [open an issue](https://github.com/salilab/conda-recipes/issues).
