package:
  name: cgal
  version: "4.9"

source:
  fn: CGAL-4.9.tar.gz
  url: https://github.com/CGAL/cgal/releases/download/releases/CGAL-4.9/CGAL-4.9.tar.xz
  sha256: 63ac5df71f912f34f2f0f2e54a303578df51f4ec2627db593a65407d791f9039

build:
  number: 1
  features:
    - vc9 [win and py27]
    - vc14 [win and py35]

requirements:
  build:
    - python [win]
    - cmake [not win]
    - cmake-mac [win]
    - boost 1.60.0 [win]
    - boost 1.61.0 [osx]
    - boost 1.57.0 [not osx and not win]
    - gmp
    - mpfr
    - zlib
  run:
    - boost 1.60.0 [win]
    - boost 1.61.0 [osx]
    - boost 1.57.0 [not osx and not win]
    - gmp
    - mpfr
    - zlib


about:
  home: http://www.cgal.org
  summary: 'The Computational Geometry Algorithms Library'
  license: GPLv3
