package:
  name: cmake
  version: 3.2.2

source:
  fn: cmake-3.2.2-win32-x86.zip [win]
  url: http://www.cmake.org/files/v3.2/cmake-3.2.2-win32-x86.zip [win]
  sha256: 8728119bbb48468ab45230a579463729e7b12d6babfa1ad77e771b239b5430db [win]

test:
  commands:
    - cmake --help

about:
  home: http://www.cmake.org/
  license: BSD
  summary: "Cross-platform, open-source build system (for Windows)"
