package:
  name: gsl
  version: 2.4 [not win]
  version: 1.8 [win]

source:
  fn: gsl-2.4.tar.gz [not win]
  url: http://gnu.mirror.vexxhost.com/gsl/gsl-2.4.tar.gz [not win]
  sha256: 4d46d07b946e7b31c19bbf33dda6204d7bedc2f5462a1bae1d4013426cd1ce9b [not win]
  fn: gsl-1.8-src.zip [win]
  url: http://downloads.sourceforge.net/project/gnuwin32/gsl/1.8/gsl-1.8-src.zip [win]
  md5: 5c0df6ca6798ef666b6f89af161b76ba [win]

build:
  number: 2
  features:
    - vc9 [win and py27]
    - vc14 [win and py35]

requirements:
  build:
    - system [linux]
    - python [win]
  run:
    - system [linux]

about:
  home: https://www.gnu.org/software/gsl/
  summary: "GNU Scientific Library"
  license: GPLv3
